Invoicer/Models/DbModels/Invoice.cs
namespace Invoicer.Models.DbModels
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using DocModels;

    public class Invoice
    {
        public Invoice()
        {
            this.Products = new HashSet<Product>();
        }

        public int ID { get; set; }
        public string DocumentID { get; set; }
        public DateTime DocumentDate { get; set; }
        public Client Client { get; set; }
        public Distributor Distributor { get; set; }
        public CurrencyEnum CurrencyID { get; set; }
        public string Weight { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
        public DateTime CreationDate { get; set; }
        public User CreatedBy { get; set; }
        public int InvoiceNumber { get; set; }
        public DateTime InvoiceDate { get; set; }
    }
}

Invoicer/Models/ViewModels/InvoiceViewModels/InvoiceViewModel.cs
namespace Invoicer.Models.ViewModels.InvoiceViewModels
{
    using System;
    using System.Collections.Generic;
    using DbModels;
    using DocModels;

    public class InvoiceViewModel
    {
        public int InvoiceNumber { get; set; }
        public DateTime InvoiceDate { get; set; }
        public ClientViewModel Client { get; set; }
        public Distributor Distributor { get; set; }
        public IEnumerable<Product> Products { get; set; }
        public double Vat { get; set; }
    }
}

Invoicer/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Mvc;

namespace Invoicer.Controllers
{
    using System;
    using System.IO;
    using System.Linq;
    using System.Text;
    using System.Text.RegularExpressions;
    using global::AutoMapper;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.EntityFrameworkCore;
    using Models.DbModels;
    using Models.ViewModels.InvoiceViewModels;
    using Services;
    using WkWrap.Core;

    // TODO
    [Route("[Controller]")]
    [Authorize]
    public class InvoiceController : BaseController
    {
        public InvoiceController(IServiceProvider serviceProvider) : base(serviceProvider)
        {
        }

        [HttpGet]
        [Route("")]
        public IActionResult Index()
        {
            var invoice = this.DbContext.Invoices
                .Include(d => d.Products)
                .Include(d => d.Client)
                .Include(d => d.Distributor)
                .Include(d => d.Distributor.Name)
                .Include(d => d.Distributor.Address)
                .Include(d => d.Distributor.Responsibles)
                .Include(d => d.Distributor.PaymentDetails)
                .First();

            var model = new InvoiceViewModel()
            {
                Products = invoice.Products.OrderBy(p => p.ProductID),
                Client = Mapper.Map<Client, ClientViewModel>(invoice.Client),
                Distributor = invoice.Distributor, // fix
                InvoiceDate = DateTime.UtcNow, // fix
                InvoiceNumber = 1, //fix
                Vat = 20, //fix
            };

            return this.View(model);
        }

        [HttpPost]
        [Route("PDF")]
        [AutoValidateAntiforgeryToken]
        public FileResult PDF(string html)
        {
            var host = this.HttpContext.Request.Scheme + "://" + this.HttpContext.Request.Host.Value;
            var matches = Regex.Matches(html, @"href=""(\/.*)"">");
            foreach (Match match in matches)
            {
                var value = match.Groups[1].Value;
                html = html.Replace(value, host + value);
            }

            var wkhtmltopdf = new FileInfo(@"C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe");
            var converter = new HtmlToPdfConverter(wkhtmltopdf);
            var settings = new ConversionSettings(
                pageSize: PageSize.A4,
                orientation: PageOrientation.Portrait,
                margins: new PageMargins(10, 5, 5, 5),
                grayscale: false,
                lowQuality: false,
                quiet: true,
                enableJavaScript: true,
                javaScriptDelay: null,
                enableExternalLinks: true,
                enableImages: true,
                executionTimeout: null);
            var pdfBytes = converter.ConvertToPdf(html, Encoding.UTF8, settings);
            string result = System.Text.Encoding.UTF8.GetString(pdfBytes);
            return File(pdfBytes, "application/pdf", "magic.pdf");
        }

        [HttpPut]
        [Route("Client/Update")]
        // TODO: [AutoValidateAntiforgeryToken]
        // TODO Check if valid model
        public IActionResult UpdateClient([Bind("ID,Vat")] Client model)
        {
            this.DbContext.Clients.Update(model);
            this.DbContext.SaveChanges();
            return this.Ok();
        }

        [HttpGet]
        [Route("Create")]
        public IActionResult Create()
        {
            Stream stream = System.IO.File.Open("../xxx.DOCX", FileMode.Open);
            // TODO DI
            var invoiceService = new InvoiceService(new VatService());
            var invoice = invoiceService.CreateInvoice(stream);
            invoice.CreatedBy = this.GetCurrentUser();
            invoice.Distributor = this.DbContext.Distributors.First();
            this.DbContext.Invoices.Add(invoice);
            this.DbContext.SaveChanges();
            return this.Ok(invoice);
        }

        public IActionResult Delete()
        {
            var invoices = this.DbContext.Invoices
                .Include(d => d.Products)
                .Include(d => d.Client)
                .Include(d => d.Client.Address)
                .ToList();
            foreach (var invoice in invoices)
            {
                this.DbContext.Remove(invoice);
            }

            this.DbContext.SaveChanges();
            return this.Ok();
        }
    }
}

Invoicer/Views/Invoice/Index.cshtml
@using Invoicer.Models.ViewModels.InvoiceViewModels
@model InvoiceViewModel
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

@await Html.PartialAsync("_InvoiceBGPartial")
@*@await Html.PartialAsync("_InvoiceENPartial")*@

@section Scripts
    {
    <script src="~/js/Scripts/Invoice/index.js"></script>
}

Invoicer/Views/Invoice/_InvoiceBGPartial.cshtml
@using Invoicer.Models.DbModels
@using Invoicer.Models.ViewModels.InvoiceViewModels
@using Invoicer.Services
@inject IConverterService ConverterService
@model InvoiceViewModel
@{
    string GetIdentityNumber(string identity)
    {
        var i = identity;
        if (string.IsNullOrEmpty(i) == false && i.ToLower().StartsWith("bg"))
        {
            i = i.Substring(2);
        }

        return i;
    }

    (string, string) GetAddressLines(IList<string> address)
    {
        var hasTown = address.Count > 1;
        var skip = hasTown ? 1 : 0;
        var town = string.Empty;
        if (hasTown)
        {
            town = address.FirstOrDefault();
        }
        return (town, string.Join(",", address.Skip(skip).ToList()));
    }
}

@using (Html.BeginForm("PDF", "Invoice", new { }, FormMethod.Post, true, new { id = "pdfInvoiceBg" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("html")
    <button id="btnSaveBg" type="button" class="btn btn-primary">Save</button>
}


<div id="invoiceBg" class="container border">
    @Html.AntiForgeryToken()
    <h1 class="text-center font-weight-bold">Фактура</h1>
    <div class="holder">
        <h2 class="text-center copy-size">Копие</h2>
        <div class="col-4">
            <div class="row">
                <div class="col-6 text-right">Номер:</div>
                <div class="col-6 text-right font-weight-bold pr-0">@Model.InvoiceNumber.ToString("0000000000")</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">Дата:</div>
                <div class="col-6 text-right font-weight-bold pr-0">@Model.InvoiceDate.ToString("dd.MM.yyyy")</div>
            </div>
        </div>
    </div>

    <div class="container mt-3">
        @Html.Hidden("ClientUri", @Url.Action("UpdateClient", "Invoice"))
        @Html.HiddenFor(m => m.Client.ID)
        <button id="updateClient" type="button" class="btn">Save</button>

        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex border-top rounded-top">
                <div class="row">
                    <div class="col-3">Получател</div>
                    <div class="col-9">
                        <div>@Html.TextBoxFor(Model.Client.Name, null, new { @class = "form-control seemless-control p-0" })</div>
                    </div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex border-top rounded-top">
                <div class="row">
                    <div class="col-3">Доставчик</div>
                    <div class="col-9">
                        @foreach (var name in @Model.Distributor.Name)
                        {
                            <div>@name.Data</div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">ДДС №</div>
                    <div class="col-9">@Model.Client.Vat</div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">ДДС №</div>
                    <div class="col-9">@Model.Distributor.Vat</div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Идент. №</div>
                    <div class="col-9">@GetIdentityNumber(Model.Client.Vat)</div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Идент. №</div>
                    <div class="col-9">@GetIdentityNumber(Model.Distributor.Vat)</div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            @{
                var clientAddress = GetAddressLines(@Model.Client.Address.ToList());
                var distributorAddress = GetAddressLines(@Model.Distributor.Address.Select(a => a.Data).ToList());
            }
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Град</div>
                    <div class="col-9">@Html.TextBox("Client_Address1", clientAddress.Item1, new { @class = "form-control seemless-control p-0" })</div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Град</div>
                    <div class="col-9">@distributorAddress.Item1</div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Адрес</div>
                    <div class="col-9">@Html.TextBox("Client_Address2", clientAddress.Item2, new { @class = "form-control seemless-control p-0" })</div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">Адрес</div>
                    <div class="col-9">@distributorAddress.Item2</div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">МОЛ</div>
                    <div class="col-9">
                        <div>@Html.TextBoxFor(m => m.Client.ResponsiblePerson, null, new { @class = "form-control seemless-control p-0" })</div>
                    </div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex">
                <div class="row">
                    <div class="col-3">МОЛ</div>
                    <div class="col-9">
                        @foreach (var person in @Model.Distributor.Responsibles)
                        {
                            <div>@person.Data</div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-between">
            <div class="col-6 border-dark border-right border-left smaller-flex border-bottom rounded-bottom">
                <div class="row">
                    <div class="col-3">Телефон</div>
                    <div class="col-9">@Html.TextBoxFor(m => m.Client.ConsultationNumber, null, new { @class = "form-control seemless-control p-0" })</div>
                </div>
            </div>
            <div class="col-6 border-dark border-right border-left smaller-flex border-bottom rounded-bottom">
                <div class="row">
                    <div class="col-3">Телефон</div>
                    <div class="col-9">@Model.Distributor.ConsultationNumber</div>
                </div>
            </div>
        </div>
    </div>

    <table class="table mt-4 table-hover border-dark border">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">№</th>
                <th scope="col" class="text-center">Код</th>
                <th scope="col" class="text-center">Наименование на стоката/услугата</th>
                <th scope="col" class="text-center">Мярка</th>
                <th scope="col" class="text-center">Количество</th>
                <th scope="col" class="text-center">Цена</th>
                <th scope="col" class="text-center">Сума</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in @Model.Products)
            {
                <tr class="border-dark border">
                    <td class="text-center border-dark border">@product.ProductID</td>
                    <td class="text-center border-dark border">@product.Code</td>
                    <td class="text-left border-dark border">@product.Description</td>
                    <td class="text-center border-dark border">@product.Measure</td>
                    <td class="text-right border-dark border">@product.Quantity.ToString("F2")</td>
                    <td class="text-right border-dark border">@product.PriceWithDiscout.ToString("F3")</td>
                    <td class="text-right border-dark border">@product.TotalAmount.ToString("F2")</td>
                </tr>
            }
        </tbody>
    </table>
    <div class="col-5 offset-7 font-weight-bold">
        @{
            var totalAmount = @Model.Products.Sum(p => p.TotalAmount);
            var vatAmount = totalAmount * Model.Vat / 100;
            var allAmount = totalAmount + vatAmount;
            <div class="row">
                <div class="col-6 text-right">Данъчна основа:</div>
                <div class="col-6 text-right">@totalAmount.ToString("F2")</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">ДДС @Model.Vat.ToString("F2")%:</div>
                <div class="col-6 text-right">@vatAmount.ToString("F2")</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">Сума за плащане:</div>
                <div class="col-6 text-right">@allAmount.ToString("F2")</div>
            </div>
        }
    </div>
    <div class="row mt-4">
        <div class="col-1 font-weight-bold pt-2">Словом:</div>
        <div class="col-11">@Html.TextBox("AmountWords", ConverterService.NumberToWords(totalAmount), new { @class = "form-control seemless-control" })</div>
    </div>
    <div class="container mt-2 border border-dark">

        @{
            var paymentDetails = @Model.Distributor.PaymentDetails.First();
        }
        <div class="row">
            <div class="col-7">
                <div class="row">
                    <div class="col-5 text-left pr-0">Дата на данъчно събитие:</div>
                    <div class="col-7 text-left">@Model.InvoiceDate.ToString("dd.MM.yyyy")</div>
                </div>
            </div>
            <div class="col-5 border-dark border-left">
                <div class="row">
                    <div class="col-4 text-left">Плащане:</div>
                    <div class="col-8 text-left">@paymentDetails.PaymentType</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <div class="row">
                    <div class="col-5 text-left">Основание на сделката:</div>
                    <div class="col-7 text-left"></div>
                </div>
            </div>
            <div class="col-5 border-dark border-left">
                <div class="row">
                    <div class="col-4 text-left">IBAN:</div>
                    <div class="col-8 text-left">@paymentDetails.IBAN</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <div class="row">
                    <div class="col-5 text-left">Описание на сделката:</div>
                    <div class="col-7 text-left"></div>
                </div>
            </div>
            <div class="col-5 border-dark border-left">
                <div class="row">
                    <div class="col-4 text-left">Банка:</div>
                    <div class="col-8 pr-1 text-left">@paymentDetails.BankName</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-7">
                <div class="row">
                    <div class="col-5 text-left">Място на сделката:</div>
                    <div class="col-7 text-left"></div>
                </div>
            </div>
            <div class="col-5 border-dark border-left">
                <div class="row">
                    <div class="col-4 text-left">Банков код:</div>
                    <div class="col-8 text-left">@paymentDetails.BankCode</div>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-3">
        <div class="col-7">
            <div class="row">
                <div class="col-2 text-left">Получил:</div>
                <div class="col-10 text-left">
                    <div>@Model.Client.ResponsiblePerson</div>
                </div>
            </div>
        </div>
        <div class="col-5">
            <div class="row">
                <div class="col-4 text-left">Съставил:</div>
                <div class="col-8 text-left">
                    @foreach (var person in @Model.Distributor.Responsibles)
                    {
                        <div>@person.Data</div>
                    }
                </div>
            </div>
        </div>

    </div>
    <div class="mt-4">
        <small>
            Съгласно чл.6, ал. 1 от Закона за счетоводството, чл 114 от ЗДДС и чл. 78 от ППЗДДС печатът и подписът не са задължителни реквизити във фактурата.
        </small>
    </div>
</div>

Invoicer/Views/Invoice/_InvoiceENPartial.cshtml
@using Invoicer.Models.DbModels
@using Invoicer.Models.ViewModels.InvoiceViewModels
@model InvoiceViewModel

@{

    (string, string) GetAddressLines(List<Address> address)
    {
        var hasTown = address.Count > 1;
        var skip = hasTown ? 1 : 0;
        var town = string.Empty;
        if (hasTown)
        {
            town = address.FirstOrDefault()?.Data;
        }
        return (town, string.Join(",", address.Skip(skip).Select(d => d.Data).ToList()));
    }
}

@using (Html.BeginForm("PDF", "Invoice", new { }, FormMethod.Post, true, new { id = "pdfInvoiceEn" }))
{
    @Html.AntiForgeryToken()
    @Html.Hidden("html")
    <button id="btnSaveEn" type="button" class="btn btn-primary">Save</button>
}

<div id="invoiceEn" class="container border">
    <div class="container">
        <div class="row">
            <div class="col-7 font-weight-bold">@Model.Distributor.Name.First().Data</div>
            <div class="col-5 text-center"><h2>Invoice</h2></div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-7">
                @{var distributorAddress = GetAddressLines(@Model.Distributor.Address.ToList());}
                <div class="row">
                    <div class="col-12 font-weight-bold">@Model.Distributor.Responsibles.First().Data</div>
                </div>
                <div class="row">
                    <div class="col-12 font-weight-bold">@distributorAddress.Item2</div>
                </div>
                <div class="row">
                    <div class="col-12 font-weight-bold">@distributorAddress.Item1</div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Phone:
                        <span class="font-weight-bold">@Model.Distributor.ConsultationNumber</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        VAT Number:
                        <span class="font-weight-bold">@Model.Distributor.Vat</span>
                    </div>
                </div>
            </div>
            <div class="col-5">
                <div class="row">
                    <div class="col-8 text-right">Invoice No:</div>
                    <div class="col-4 text-right font-weight-bold pr-0">@Model.InvoiceNumber.ToString("0000000000")</div>
                </div>
                <div class="row">
                    <div class="col-8 text-right">Date:</div>
                    <div class="col-4 text-right font-weight-bold pr-0">@Model.InvoiceDate.ToString("dd.MM.yyyy")</div>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-2 container">
        <div class="row justify-content-between">
            <div class="col-6 border-dark border rounded smaller-flex">
                <div class="row">
                    <div class="col-2 pr-0">Bill To:</div>
                    <div class="col-10 text-left font-weight-bold">
                        <div class="row">
                            <div class="col-12 mb-3">@Model.Client.Name.First().Data</div>
                        </div>
                        @foreach (var address in Model.Client.Address)
                        {
                            <div class="row">
                                <div class="col-12">@address.Data</div>
                            </div>
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Phone:
                        <span class="font-weight-bold pl-4">@Model.Client.ConsultationNumber</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        VAT Number:
                        <span class="font-weight-bold pl-2">@Model.Client.Vat</span>
                    </div>
                </div>
            </div>
            <div class="col-6 border-dark border rounded smaller-flex">
                <div class="row">
                    <div class="col-2 pr-0">Ship To:</div>
                    <div class="col-10 text-left font-weight-bold">
                        <div class="row">
                            <div class="col-12 mb-3">@Model.Client.Name.First().Data</div>
                        </div>
                        @foreach (var address in Model.Client.Address)
                        {
                            <div class="row">
                                <div class="col-12">@address.Data</div>
                            </div>
                        }
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        Phone:
                        <span class="font-weight-bold pl-4">@Model.Client.ConsultationNumber</span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <table class="table mt-4 table-hover border-dark border">
        <thead class="thead-dark">
            <tr>
                <th scope="col" class="text-center">№</th>
                <th scope="col" class="text-center text-nowrap">Product ID</th>
                <th scope="col" class="text-center">Description</th>
                <th scope="col" class="text-center">Unit</th>
                <th scope="col" class="text-center">Quantity</th>
                <th scope="col" class="text-center text-nowrap">Unit Price</th>
                <th scope="col" class="text-center">Amount</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var product in @Model.Products)
            {
                <tr class="border-dark border">
                    <td class="text-center border-dark border">@product.ProductID</td>
                    <td class="text-center border-dark border">@product.Code</td>
                    <td class="text-left border-dark border">@product.Description</td>
                    <td class="text-center border-dark border">Item</td>
                    <td class="text-right border-dark border">@product.Quantity.ToString("F2")</td>
                    <td class="text-right border-dark border">@product.PriceWithDiscout.ToString("F3")</td>
                    <td class="text-right border-dark border">@product.TotalAmount.ToString("F2")</td>
                </tr>
            }
        </tbody>
    </table>

    <hr class="border-dark border-bottom" />

    <div class="col-5 offset-7 font-weight-bold">
        @{
            var totalAmount = @Model.Products.Sum(p => p.TotalAmount);
            var vatAmount = totalAmount * Model.Vat / 100;
            var allAmount = totalAmount + vatAmount;
            <div class="row">
                <div class="col-6 text-right">Subtotal:</div>
                <div class="col-6 text-right">@totalAmount.ToString("F2")</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">VAT:</div>
                <div class="col-6 text-right">@vatAmount.ToString("F2")</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">Currency:</div>
                <div class="col-6 text-right">EUR</div>
            </div>
            <div class="row">
                <div class="col-6 text-right">Total:</div>
                <div class="col-6 text-right">@allAmount.ToString("F2")</div>
            </div>
        }
    </div>

    <div class="container">
        <div class="row">
            <div class="col-2 font-weight-bold">Deal Details:</div>
            <div class="col-10 pl-0"></div>
        </div>
        <div class="row mt-1">
            <div class="col-2 font-weight-bold">Bank Details:</div>
            <div class="col-10 pl-0"></div>
        </div>
        @{ var paymentDetails = Model.Distributor.PaymentDetails.First();}
        <div class="row">
            <div class="col-2">Bank:</div>
            <div class="col-10 pl-0 font-weight-bold">@paymentDetails.BankName</div>
        </div>
        <div class="row">
            <div class="col-2">IBAN:</div>
            <div class="col-10 pl-0">@paymentDetails.IBAN</div>
        </div>
        <div class="row">
            <div class="col-2">Bank code:</div>
            <div class="col-10 pl-0">@paymentDetails.BankCode</div>
        </div>
    </div>

    <div class="mt-2 text-center">Thank you for your business!</div>
</div>